# Generated by Django 2.1.7 on 2019-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='reg_token',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invite',
            name='reg_token_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
