# Generated by Django 2.1.7 on 2019-04-03 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190403_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 14, 24, 55, 695488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 14, 24, 55, 683490, tzinfo=utc)),
        ),
    ]
