# Generated by Django 2.1.7 on 2019-04-17 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190327_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
